highlighter: None
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: atom.xml

exclude:
  - .vendor/
  - .pre-commit-config.yaml
  - .gitignore
  - requirements.txt
  - build_image
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - jekyll.sh
